services:
  firebase-emulators:
    image: andreysenov/firebase-tools:latest
    ports:
      - "8080:8080"
      - "4000:4000"
      - "9099:9099"
    volumes:
      - ./firebase.json:/home/node/firebase.json
    environment:
      - GCP_PROJECT=flameql-test
    command: firebase emulators:start --project flameql-test
